sudo: false
language: c
compiler: gcc
if: tag IS blank
script: /usr/lib/x86_64-linux-gnu/rerun/travis-ci-modules.sh
notifications:
  irc:
  - irc.freenode.org#rerun
addons:
  apt:
    packages:
    - markdown
    - fakeroot
    - build-essential
    - devscripts
    - dh-make
    - libfile-fcntllock-perl
    - rpm
    - xmlstarlet
    - jq
    - rerun
    - rerun-bintray
    sources:
    - sourceline: deb https://dl.bintray.com/rerun/rerun-deb /
env:
  global:
  - MY_REPO=github.com/rerun-modules/rerun-docker
  - TRAVISCI_SKIP_TESTS=true
  - BINTRAY_USER=stagrlee
  - BINTRAY_ORG=rerun
  - secure: Ja0NIojvJUYZuTjZ4HL0nuhR+tOdN1PTGCnmwolXII1yCgX/YlzbzjoLLBKwrA4y9DT9ZUc1gXeptnkWARGBb6yw/F69xv2JkUvgJh49c7ZJW01aObK+bZe0gbt7V8cDewFK3ottt5dEDe99XwrLqipDTnGmbzh3jj34YZWy3UTDFWWcKn8ssTx0QeAy/Drz6oqJeW5XZEIi3ABoRHG5yx4eC0LKTEr+GnLj4AbsqpbdBIqjE3ncUb4GncJWKjXluudYtWsDG7YhnQa/x8QQtB7WEj1HpDrXM0ml8lTTJg1CXmquaTAL5S4HaLwELecMrwVwXyn08x/GiaRB1/xzCqNygb4y+xWNhz3+yPDhuBpcDw4C23DMzZi+0EjhMxRcU09Vt+C3Ix1Td50WQR5nx4T7Tl0yrruF4mmAF6cNi8QsiI4ZxS1aYQnuVcfuI50EAj42RPJ5CSSANEcVfmJ5wTIkXaxMIEzNzXZ7L2kMzmlzzqMWFFULY5pSPNfM+8clB6sfIu80jpD4Zv+Hta7zR+4Kq/4HogB6fi70UJHIDpqSfFmCQVg9iRRi6jYdVpOaL7p+AdH9s5Dyv7EMV1DALVBJkC41V0H4L11oxJuLevhsUY8irA4oH9MI/napPbkTvfGBwKYAQqHLN56RH8HcL3kt2fg+g7dyaOE3X0/+cBI=
  - secure: wzuHYtktwl7IAXUQEblOci18WAHVW591bgFR/bl3A8CJQfhbKJcgsZeupTSKPn9tBGSQbwJYrHJgEOPZSLoY0s3FTAFj3SkusP0dNKUMJf1gc1MC+KK54jIQzaSXL+vhTP2EgOg/4PCmg6R+V1vfYyiH7F+edHmFdczRZ8RS39HeWZWBSFKKSnAAg4+2YmAk4ixN+wllGUnK4vIBdYTHBiVJJ6fWe39SZIruB7rVLZainynageAGBNlh1H/ZJJab/56E0N3v9XuOuIDN+mvOrduSpLr4vnWCSoJuLP8OeWKT2M1KBHvZsXne4r9Tqh6dIzvFCXnokbScXX/w3zeYnoi8C+HyHPYikzMkaJ0X8UJGloi+AFJc2ML9rHELON/jt6ZIbVVmd7Nr7DjgaEYXQ69aJx7zlni+oNhBXXp99n8pr1+24jeIGeND/oBb35Ib70zywe/OOdMz3X5Aue5V/zhWo5ztrzPq8FT2YzKSSi/atqSvztPxGNksocwEpDAcmX3Qc13Bh2ZsUgcwM+yZD8tGgPg+4Nczx0iJqGjEOMSlU8ZwjtTA8L0VoAC9FQ1QEIiD77cCDswgMoA6/822eAnS0f4lJNRr4Zxn02tCwSGO2EAbPFF/7K1IApa94BQ3QEXJIAl4HZGrN1NwHRCbkdVKMW2fFopjzubh2GrNWPk=
