sudo: false
language: c
compiler: gcc
if: tag IS blank
script: /usr/lib/x86_64-linux-gnu/rerun/travis-ci-modules.sh
notifications:
  irc:
  - irc.freenode.org#rerun
addons:
  apt:
    packages:
    - markdown
    - fakeroot
    - build-essential
    - devscripts
    - dh-make
    - libfile-fcntllock-perl
    - rpm
    - xmlstarlet
    - jq
    - wget
    - zip
    - rerun
    - rerun-bintray
    sources:
    - sourceline: deb https://dl.bintray.com/rerun/rerun-deb /
env:
  global:
  - MY_REPO=github.com/rerun-modules/rerun-docker
  - TRAVISCI_SKIP_TESTS=true
  - BINTRAY_USER=stagrlee
  - BINTRAY_ORG=rerun
  - secure: W6TEdQlrKm8C0NDtXSR/QYOjgWVjF0JLJFeyhvsVTGnarZQ4L/VxM31SBdYyJvGNAvoKkQIf+mWyTpOnbCT8l4lJnsVjtQoZnaQx6Ba1nS3sYoswjelAN/7VVLMOk/lZNycehYYelJm3qo9N+pxDorvgxn+CoE6uZAv1koPgs9xaeSjzy+3RoH53UKl9R/qJSG7t5Ew9PQkEJoSIDdwMFnselWs98ABbG2N34vrr6Ss2amq17BlR0XXL+nv/mIH3K1dsDrTzTfyCPamIEnmbne6IpsV20Jqan+m5nFNWx5FkEp6MLrsCDmYP48WiabXQXHTzANl6iN9Gdgp4bTKInhSt7HtvqYqW4kmgMrBU3NJNY9iXcLptlhLeaEqRvKbGVe6JFezWp+yloc/szeYavWDjCmg7JVENOvNvV9bHJdACvviTYX52Gppf4UW/vdTegvPdMgg25VvgB7vO/83r57hqBlaGjkYjBFmzzN9MzAlOL5TeuPnzcekJOBGuPzcVLeQIngdbzUOxb7I2luSzslCt/+En7bGU3BHd40YNCSVSJ3woZb/LCek1YXOwI5jxSUgu0zryct0laY8ZPpi9KCmOZ10DhSLZVBYBHuBXeAB8XCkJSInthaOPdshu49kjQcufLMcwK/zGMOw2yFCIZv//U14l4iqpZEoJ0JxlqJ0=
  - secure: wzuHYtktwl7IAXUQEblOci18WAHVW591bgFR/bl3A8CJQfhbKJcgsZeupTSKPn9tBGSQbwJYrHJgEOPZSLoY0s3FTAFj3SkusP0dNKUMJf1gc1MC+KK54jIQzaSXL+vhTP2EgOg/4PCmg6R+V1vfYyiH7F+edHmFdczRZ8RS39HeWZWBSFKKSnAAg4+2YmAk4ixN+wllGUnK4vIBdYTHBiVJJ6fWe39SZIruB7rVLZainynageAGBNlh1H/ZJJab/56E0N3v9XuOuIDN+mvOrduSpLr4vnWCSoJuLP8OeWKT2M1KBHvZsXne4r9Tqh6dIzvFCXnokbScXX/w3zeYnoi8C+HyHPYikzMkaJ0X8UJGloi+AFJc2ML9rHELON/jt6ZIbVVmd7Nr7DjgaEYXQ69aJx7zlni+oNhBXXp99n8pr1+24jeIGeND/oBb35Ib70zywe/OOdMz3X5Aue5V/zhWo5ztrzPq8FT2YzKSSi/atqSvztPxGNksocwEpDAcmX3Qc13Bh2ZsUgcwM+yZD8tGgPg+4Nczx0iJqGjEOMSlU8ZwjtTA8L0VoAC9FQ1QEIiD77cCDswgMoA6/822eAnS0f4lJNRr4Zxn02tCwSGO2EAbPFF/7K1IApa94BQ3QEXJIAl4HZGrN1NwHRCbkdVKMW2fFopjzubh2GrNWPk=
