sudo: false
language: c
compiler: gcc
if: tag IS blank
script: /usr/lib/x86_64-linux-gnu/rerun/travis-ci-modules.sh
notifications:
  irc:
  - irc.freenode.org#rerun
addons:
  apt:
    packages:
    - markdown
    - fakeroot
    - build-essential
    - devscripts
    - dh-make
    - libfile-fcntllock-perl
    - rpm
    - xmlstarlet
    - jq
    - rerun
    - rerun-bintray
    sources:
    - sourceline: deb https://dl.bintray.com/rerun/rerun-deb /
env:
  global:
  - MY_REPO=github.com/rerun-modules/rerun-docker
  - TRAVISCI_SKIP_TESTS=true
  - BINTRAY_USER=ahonor
  - BINTRAY_ORG=rerun
  - secure: bljg91Y8Q5u1SJ/P/5jCyR43tw6s5Yhav1SnY87UjUCs7v9JYDjnm5Z/AYheSucsQWBzS2CC3mxV3GT7ZNZE9Ae2KRPa/h9oFjaiKxXdXDdfVGFM1BcgUzQUv++QAIxirMduIMlHXreNilJovQ9jEKwinTDBFwRAoIBzFPUDC9mNwyb5J57iGjgCU1c9nPQFkgWiycFquYK+45GAyq1TgTiRIR7oH7tbb6Zk346PDL4edUO62tuYtjJ20wv43BaX7h9Xq2dq2EdMy92pNf3mEMeCNrPsl0N0lRL8BNIR3BPFMemZD9F6ZDClmmuSaYoh5e4WGxHKWEkM7JGf+Z8VLNiAWdO9a95Rf13NzJxn+SlBqLGHtU8itfECmDsoK07E3fiBeNW1e4I+v8rzJehlWkI3YqnjuRi9JnlkxT6kX4BPALNN0Eq08LIM6dtRV+QXeSpaWRw6MsfbMuMN+O4ck++QLr1udS+5cnFZOgk2rJV9LyDqGNeqJQycZcXulvIc6yhHZLxxJc4M92zKUcSQC30yugbugcn1cruOsILn4uWkrPeM61adQ6KFEQ02VCrZXNIFjC3uU+iVVNStBXPR/6711l6/a+UbVSCGe1yl63tlCqVPhXTqTuq2viuoVNedfN0fKhTRURfUMnNE688VB9MilTZXnNOIJZHtbNjry8o=
  - secure: wzuHYtktwl7IAXUQEblOci18WAHVW591bgFR/bl3A8CJQfhbKJcgsZeupTSKPn9tBGSQbwJYrHJgEOPZSLoY0s3FTAFj3SkusP0dNKUMJf1gc1MC+KK54jIQzaSXL+vhTP2EgOg/4PCmg6R+V1vfYyiH7F+edHmFdczRZ8RS39HeWZWBSFKKSnAAg4+2YmAk4ixN+wllGUnK4vIBdYTHBiVJJ6fWe39SZIruB7rVLZainynageAGBNlh1H/ZJJab/56E0N3v9XuOuIDN+mvOrduSpLr4vnWCSoJuLP8OeWKT2M1KBHvZsXne4r9Tqh6dIzvFCXnokbScXX/w3zeYnoi8C+HyHPYikzMkaJ0X8UJGloi+AFJc2ML9rHELON/jt6ZIbVVmd7Nr7DjgaEYXQ69aJx7zlni+oNhBXXp99n8pr1+24jeIGeND/oBb35Ib70zywe/OOdMz3X5Aue5V/zhWo5ztrzPq8FT2YzKSSi/atqSvztPxGNksocwEpDAcmX3Qc13Bh2ZsUgcwM+yZD8tGgPg+4Nczx0iJqGjEOMSlU8ZwjtTA8L0VoAC9FQ1QEIiD77cCDswgMoA6/822eAnS0f4lJNRr4Zxn02tCwSGO2EAbPFF/7K1IApa94BQ3QEXJIAl4HZGrN1NwHRCbkdVKMW2fFopjzubh2GrNWPk=
