#!/usr/bin/env bash

#/ command: docker:clean-all: "Clean everything (docker containers, images, and vfs files)"
#/ usage: rerun docker:clean-all [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh clean-all || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

rerun_log info "Cleaning up docker (based on http://blog.yohanliyanage.com/2015/05/docker-clean-up-after-yourself/)"

rerun docker: clean-containers
rerun docker: clean-images

docker volume rm $(docker volume ls -qf dangling=true)

if [ "$?" != "0" ]; then
  rerun_log info "If you are running docker earlier than 1.9, that may have caused this error.  If so, you can manually run:"
  rerun_log "docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes"
fi

# Done. Exit with last command exit status.
exit $?

