# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Nov 11 14:11:57 EST 2015
#
#/ usage: docker:exec [ --mount </opt>]

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --mount) rerun_option_check $# $1; MOUNT=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$MOUNT" ] && MOUNT="$(rerun_property_get $RERUN_MODULE_DIR/options/mount DEFAULT)"
    # Check required options are set

    # If option variables are declared exportable, export them.
    export MOUNT
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${MOUNT:=}


