#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below.

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
#
#/ command: docker:update-hosts: "Update local /etc/hosts file with container IP addresses"
#/ usage: rerun docker:update-hosts [options]

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh update-hosts || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status.

#trap 'rerun_die $? "*** command failed: docker:update-hosts. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

rerun_log "Updating hosts file with current container IP addresses"
sudo sed -i '/172\./d' /etc/hosts
if [ `docker ps -q | wc -l` != 0 ]; then
  docker ps -q | xargs -n 1 docker inspect  | jq 'map({(.NetworkSettings.IPAddress):   (.Name)})' | sed 's#[\/":]##g' | grep 172 | cut -b 4- | sed 's/server_//' | sed 's/_1//' | gawk '{ print $1 "\t" $2 " " $2 ".service.pharmright.consul" }' | sudo tee -a /etc/hosts
fi

# Done. Exit with last command exit status.
exit $?

