#!/usr/bin/env bash

#/ command: docker:get-image: "Get the image of a container using the friendly name"
#/ usage: rerun docker:get-image [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. $RERUN_MODULE_DIR/lib/functions.sh get-image || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

docker inspect --format "{{ .Image }}" "$1"

# Done. Exit with last command exit status.
exit $?

